### ISSUE TITLE
Tests fail with `misaligned pointer dereference: address must be a multiple of 0x8`

### ISSUE THREAD

**Issue by GyulyVGC** [wacker-dev/waki#6]
I found out about your library this morning while I was facing a bunch of problems trying to use `reqwest` in a WIT-component-based environment.

This library fixes the issues I had like a charm and correctly works when I invoke the WIT exports in JavaScript.

However, I later tried to write down some tests in Rust to verify some simple HTTP requests, but they panic with the error `misaligned pointer dereference: address must be a multiple of 0x8`.

So I'm wondering whether this is a subtle bug or simply this library is not supposed to work in standard Rust.

I've also tried running my tests with `--target wasm32-wasi` but they don't even start.

**Comment by iawia002** [comment]
What are your tests like, and how are they run? Theoretically, it can be tested because waki itself has integrated tests. However, unlike ordinary tests, it requires a special way to run:

1. Write separate test programs.
    * https://github.com/wacker-dev/waki/blob/main/test-programs/src/bin/client_get_with_query.rs
    * https://github.com/wacker-dev/waki/blob/main/test-programs/src/bin/server_hello.rs
2. Compile the above programs into WASM files.
    * https://github.com/wacker-dev/waki/blob/main/test-programs/artifacts/build.rs
3. Use [wasmtime](https://github.com/bytecodealliance/wasmtime) (or another runtime that supports WASI preview 2 API) to run these test programs.
    * https://github.com/wacker-dev/waki/blob/main/waki/tests/all/main.rs

**Comment by GyulyVGC** [comment]
Thank you so much for the directions.
I was running them with `cargo test` just like ordinary tests.
I'll take inspiration from your workflow 👍
